[project]
name = "qv_simple_chat_app"
version = "0.1.0"
description = "Simple chat app using Ollama and NiceGUI"
readme = "README.md"
dependencies = [
    "nicegui",
    "qv-ollama-sdk",
    "ollama"
]
